spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rathinam_toastmasters}
    username: ${SPRING_DATASOURCE_USERNAME:pravin}
    password: ${SPRING_DATASOURCE_PASSWORD:Ratnaa@06}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expirationMs: 86400000

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173
